### PR TITLE
Update to aws-c-sdkutils v0.1.11

### PR DESCRIPTION
**Pull request by dannycjones**
Small change, fixes the priority on the AWS profile credential config.

This will allow us to remove the following temp code in a subsequent PR to get around the issue:

https://github.com/awslabs/mountpoint-s3/blob/91df4c441b507aefc3c8421d13881589378fa740/mountpoint-s3-client/tests/auth.rs#L146-L148

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and I agree to the terms of the [Developer Certificate of Origin (DCO)](https://developercertificate.org/).

### CODE REVIEW

**Review by sauraank — APPROVED** [review]
Should not we now remove the lines 146 to 148 from `mountpoint-s3-client/tests/auth.rs`?

**Comment by sauraank** [comment]
Fuse Tests of fuse_tests::unlink_test::unlink_writehandle_test_mock::prefix is failing. Should I revert back the approval?

**Comment by dannycjones** [comment]
> Should not we now remove the lines 146 to 148 from `mountpoint-s3-client/tests/auth.rs`?

I have another PR for this, I want to keep CRT updates isolated.

**Comment by dannycjones** [comment]
> Fuse Tests of fuse_tests::unlink_test::unlink_writehandle_test_mock::prefix is failing. Should I revert back the approval?

Looking into this already. We cannot merge with the test failing. I suspect we have some transient issue to investigate separately.

**Comment by dannycjones** [comment]
I've merged this, but I do need to follow up to understand why the test is non-deterministic.

**Pull request merged**
